### ISSUE TITLE
Feature request: Tab completion

### ISSUE THREAD

**Issue by SlimeDog** [TeamVK/CoordinateTool#1]
Please implement appropriate tab completion for commands. For example
`/ct <tab> <tab>` should produce `/ct {current_X} {current_Z}`
rather than `/ct {playerName} {playerName}`

**Comment by vk2gpz** [comment]
The current plugin does not have any tabcontrol override. so, it's showing whatever bukkit is providing.
I will add proper override at some stage.

**Comment by vk2gpz** [comment]
added.

**Comment by vk2gpz** [comment]
tab complete method has been added.

**Comment by SlimeDog** [comment]
Confirmed fix in CoordinateTool-3.5.2. Thanks.
