### ISSUE TITLE
PAPI placeholders unregistered on papi reload

### ISSUE THREAD

**Issue by SlimeDog** [TeamVK/CoordinateTool#2]
Paper 1.19.3-420
CoordinateTool 3.5.1
PAPI-CoordinateTool-2.1.0.jar not installed

So, placeholders should be registered by CoordinateTool.

`/papi parse me %coordinatetool_file%` returns `%coordinatetool_file%` not the current region filename.
`/papi parse me %coordinatetool_chunk%` returns `% coordinatetool_chunk%` not the current chunk.

**Comment by vk2gpz** [comment]
sounds like you reloaded papi after coordinatecontol was loaded.

**Comment by SlimeDog** [comment]
Yes. But one needs to be able to reload PAPI, in any event. What should I do?

**Comment by SlimeDog** [comment]
Perhaps `ct reload` should unregister and re-register the placeholders.

**Comment by vk2gpz** [comment]
I will add PlaceholderAPI in softdepend.  As long as papi was loaded before CT, it works.
I'm not sure how PAPI's reload command behave.  It should not clear expansions, which were registered from external plugins.  But it sounds like it does clear the complete expansion list kept internally.  I will think of somthing.

**Comment by SlimeDog** [comment]
For unrelated reasons, I need to execute `papi reload` at the end of server startup. I now follow that with unload/load CoordinateTool. Problem solved, for my particular case.

You probably want to address the general case. It is really convenient to be able to reload PAPI after updating the expansions on a running server.

**Comment by SlimeDog** [comment]
BTW, `onEnable` logs `[PlaceholderAPI] Successfully registered expansion: coordinatetool [${project.version}]`

**Comment by vk2gpz** [comment]
Thanks, this should match with CoordinateTool's version number now.

**Comment by SlimeDog** [comment]
Paper 1.19.3-420
CoordinateTool 3.5.2
RealScoreboard 1.0

CT placeholders remain unregistered after `papi reload`, even when followed by `ct reload` and then `realscoreboard reload`. Other non-PAPI-expansion placeholders are re-registered; for example BiomeRemap `biomeremap_biome_name`.

**Comment by vk2gpz** [comment]
use 3.5.3, papi expansion should be persistent.

**Comment by SlimeDog** [comment]
Perfect. Thanks.

**Comment by vk2gpz** [comment]
ya, thanks for pointing that out.  I've been using external papi extension, so it never occurred to me to check persist() method.
