### ISSUE TITLE
PAPI thinks that CoordinateTool is out-of-date

### ISSUE THREAD

**Issue by SlimeDog** [TeamVK/CoordinateTool#3]
Paper 1.19.3-420
PlaceholderAPI 2.11.3-DEV-165
CoordinateTool 3.5.3, PAPI expansion not installed

```
> papi ecloud list installed
[22:56:18 INFO]: Installed Expansions
     Name            Author   Verified  Version  
-------------------------------------------------
1.   CoordinateTool  vk2gpz   Y         3.5.3    
...
```
but available PAPI CoordinateTool expansion is version 2.1.0.

This may be because an expansion is provided on the PAPI site. Note that other non-expansion placeholder providers are not listed by this command.

**Comment by vk2gpz** [comment]
I don't thing papa eCloud site let me delete already published papa modules.

**Comment by SlimeDog** [comment]
Probably not. And they are needed for previous CoordinateTool versions.

You could update the expansion module to have the same version as CoordinateTool, presently 3.5.3.

**Comment by vk2gpz** [comment]
If users haven't updated the CoordinateTool, they can keep using the latest available on the eCloud.
I switched to not using eCloud since they introduced a recurring verification process.  This newly added process adds a manual request to eCloud team to very my resource.  It breaks my automated deploy process, so I moved all plugin-based expansion modules to the plugin side.

**Comment by vk2gpz** [comment]
As for the PAPI thinking the expansion module is out of date.   As long as the plugin-proived version is newer than ones available on eCloud, that should not cause the issue, since eCloud's update or download function should not override the persistent plugin-provided expansion. 

If not having the same version as the plugin-provided one on eCloud is going to be an issue, I will update one on eCloud.

**Comment by SlimeDog** [comment]
![Screen Shot 2023-02-26 at 12 38 28 PM](https://user-images.githubusercontent.com/17748923/221435846-02e85256-576e-469e-bf7a-629d73ccb609.png)

As you can see, `papi ecloud list installed` thinks CoordinateTool is out-of-date. Up-to-date would be green.

**Comment by vk2gpz** [comment]
oh, the yellow indicates out-of-date??  but the version number is newer... Shouldn't PAPI ecloud class be able to simple version number comparisons?? or not compare the plugin-provided expansion against eCloud resources?

Maybe, PAPI should implement that.  I hate having multiple sources, which could potentially cause a mismatch. 
I want to check PAPI code...

**Comment by vk2gpz** [comment]
hmm, maybe I missed something and my plugin-provided papi expansion is making papi ecloud to think it's an eCloud resoruce.

**Comment by vk2gpz** [comment]
ah, they're just doing equalsIgnoreCase check against the latest version string on the eCloud.... no actual version comparison.

**Comment by SlimeDog** [comment]
> hmm, maybe I missed something and my plugin-provided papi expansion is making papi ecloud to think it's an eCloud resoruce.

That might be the issue. As I mentioned above, other non-expansion placeholder providers are not listed by this command.

**Comment by vk2gpz** [comment]
it checks the locally registered expansion's name against ecloud entries.  If the name is present on eCloud, it does simple string match against the latest version string.  

What I might do is submit a patch, which includes a "persist" check.  If the locally installed expansion is set as a persistent expansion, this eCloud check does not need to happen.

**Comment by SlimeDog** [comment]
Hmmm. I have no idea how the other placeholder providers are tagged.

**Comment by vk2gpz** [comment]
they just need to change:
if (local.isRegistered()) {
to
if (local.isRegistered() && !local.persist()) {

in CloudExpansionManager class.

**Comment by vk2gpz** [comment]
I submitted a PR on PlaceholderAPI.

**Comment by SlimeDog** [comment]
> Hmmm. I have no idea how the other placeholder providers are tagged.

I meant that to suggest that there may be other uses for `.persist()`. We'll see.

**Comment by vk2gpz** [comment]
ok, my PR has been merged into PAPI's master.
However, I also suggested they set the version number convention for expansions so that they can implement a proper version number check method rather than simply doing equalsIgnoreCase.

Once they implement that they can check persist() and also versionCeck().

**Comment by SlimeDog** [comment]
Great! I will wait for a release. I don't run dev builds of PlaceholderAPI. Too many issues doing that in the past.

**Comment by SlimeDog** [comment]
Actually, your wiki PR was merged. The `persist()` PR has not been merged yet.

**Comment by vk2gpz** [comment]
> > Hmmm. I have no idea how the other placeholder providers are tagged.
> 
> I meant that to suggest that there may be other uses for `.persist()`. We'll see.

well, The document of persist() method clearly states that the plugin-provided expansion should set it to true to avoid missing from reload process.  If an expansion is provided externally, there is no point in eCloud intervening.

Unless, the developer decided to move from locally provided to eCloud and eCloud one is newer.

Hence, I suggested PAPI team to come up with a proper versioning scheme and version check method.

**Comment by vk2gpz** [comment]
> Actually, your wiki PR was merged. The `persist()` PR has not been merged yet.

ah, yes, PR was just approved at this stage.

**Comment by vk2gpz** [comment]
Ok, this fix wont' come in for a while.  I withdrew my PR and submitted a bug issue ticket instead so that they can fix it.
I am fed up with this guy who just argues about anything.

let's hope they actually implement a version check rather than equalsIgnoreCase().

**Comment by SlimeDog** [comment]
That would be the best approach. Thanks for trying.

**Comment by vk2gpz** [comment]
I gave up on that asking PAPI to fix the issue.  If you want this issue fixed, I suggest you submit a report (bug, PR, whatever).  I cannot waste my time trying to justify myself to someone going in a circle and overcomplicating things.

**Comment by vk2gpz** [comment]
sorry that I could not do anything from my end.

**Comment by SlimeDog** [comment]
Well, you could post version 3.5.3 of the expansion, and keep the expansion in sync with CT. Then the (faulty) PAPI report display the correct color-coding.

**Comment by vk2gpz** [comment]
well. when the latest version always comes with the plugin, maintaining a duplicate release is redundant and my time should be used for the more meaningful things. ;)

**Comment by vk2gpz** [comment]
that's really their bug (using equalsIgnoreCase for version comparison).

**Comment by SlimeDog** [comment]
I understand. That just seems an easy workaround. But it's not my time.
